Ложкин 2.1.10
GePeKA/HT-ITIS.2.1-student pull request #11
Opened 2023-11-22 19:27 UTC by GePeKA

2023-11-22 20:05 UTC, k0c0w submitted a review, later dismissed
Остальные сервисы просто скопировал же?

2023-11-22 20:05 UTC, k0c0w commented on Homework10/Hw10/Services/CachedCalculator/MathCachedCalculatorService.cs
> +		var cachedExpression = _dbContext.SolvingExpressions.FirstOrDefault(x => x.Expression == expression);
Синхронный доступ к бд, блокирует поток

2023-11-22 20:18 UTC, k0c0w requested changes

2023-11-22 20:18 UTC, k0c0w commented on Homework10/Hw10/Services/MathCalculator/MathCalculatorService.cs
> +    public IExpressionParserService ExpressionParser { get; set; }
```suggestion
    public IExpressionParserService ExpressionParser { get; }
```

2023-11-22 20:22 UTC, k0c0w requested changes
Остальное же просто скопировал?

2023-11-22 20:22 UTC, k0c0w commented on Homework10/Hw10/Services/CachedCalculator/MathCachedCalculatorService.cs
> +		var cachedExpression = _dbContext.SolvingExpressions.FirstOrDefault(x => x.Expression == expression);
Синхронный доступ к бд, бдокирует поток

2023-11-22 20:22 UTC, k0c0w commented on Homework10/Hw10/Services/MathCalculator/MathCalculatorService.cs
> +    public IExpressionParserService ExpressionParser { get; set; }
```suggestion
    public IExpressionParserService ExpressionParser { get; }
```

2023-11-22 20:28 UTC, GePeKA commented
> Остальное же просто скопировал?

Да

2023-11-22 20:36 UTC, GePeKA commented
А как это некорректно создал ревью реквест? 🤔

2023-11-23 16:31 UTC, k0c0w commented
> А как это некорректно создал ревью реквест? 🤔

Это я неправильно сделал, без причины не закрывалось меню

2023-11-23 16:33 UTC, k0c0w approved these changes

2023-11-23 16:33 UTC, merged